### PR TITLE
feat(log): add a log package

### PR DESCRIPTION
**Pull request by arschles**
For conveniently logging colorful messages for humans to read

TODO:
- [x] Move from using `github.com/labstack/gommon` to `github.com/deis/pkg/prettyprint`

### CODE REVIEW

**Comment by mboersma** [comment]
Doesn't our `github.com/deis/pkg/prettyprint` package also do similar colorization?

**Comment by arschles** [comment]
`prettyprint` has colorization logic and this is higher level logging logic (similar to `github.com/helm/helm/log`). On a quick look, I think this could be ported from using `github.com/labstack/gommon/color` to `prettyprint`. Thoughts on doing so?

**Comment by mboersma** [comment]
My only thought was to keep things [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) if possible, which would mean using `prettyprint` instead of `gommon/color`. (Unless their interfaces are radically different or to do so would be a lot of work. Practicality beats purity in my book.)

**Comment by arschles** [comment]
@mboersma that'd be fine. I've added a TODO to this PR to make the move, and I'm going to leave it open for now.

**Comment by technosophos** [comment]
I agree about the color thing, and would LOVE to see this package committed.

**Comment by arschles** [comment]
@technosophos @mboersma I've refactored this code to use `github.com/deis/pkg/prettyprint`, refactored the package a bit, and added package docs. This PR is ready for review now

**Comment by arschles** [comment]
This had build issues and was trying to build & test everything (including `vendor`), fixed in https://github.com/arschles/deis-pkg/commit/8839df04dab2477df2275fc033163dc8788c2f76 and https://github.com/deis/pkg/commit/e9e1986340f99c0a5fc2bbb187909448e19ceec2 cc/ @mboersma @technosophos

**Comment by mboersma** [comment]
Last set of build tweaks looks fine to me. :ship:

**Pull request merged**
