### PR TITLE
fix(glide.yaml): regenerate lock with Glide 0.9.1

### PR DESCRIPTION
**Pull request by technosophos**

### CODE REVIEW

**Comment by technosophos** [comment]
Does anyone know why we're running our tests against the tip of Go's dev tree? Go 1.7 (which is nowhere near being released) removes the GO15VENDOREXPERIMENT flag. So the travis error is totally spurious right now.

https://github.com/golang/go/commit/3e23442518d9c66def2ae48f83026e29c5f26609

**Comment by technosophos** [comment]
Depends on #23

**Comment by mboersma** [comment]
> running our tests against the tip of Go's dev tree?

Because "1.4, 1.5, tip" is a pretty common pattern for Travis CI--I think it's in their example docs even. Now that 1.7 is tip, I guess that broke. I'll fix it in a PR. _Update_: see #24, or just make the same change in this PR. _Update 2_: D'oh #23.

**Comment by Joshua-Anderson** [comment]
Glide 0.9.1 is pretty old now. Since this PR is quite stale, I'm going to close it. I think @kmala is in the process of updating `pkg` so the lockfile should get regenerated then.

**Pull request closed without merging**
