### PR TITLE
ref(glide): use client-go

### PR DESCRIPTION
**Pull request by bacongobbler**
This PR refactors deis/pkg to use client-go and to stop relying on k8s v1.2.4 as the pinned release.

### CODE REVIEW

**Comment by vdice** [comment]
This looks good.  However, I'm assuming the implications of this change are widespread among the various Deis Workflow components.  What should the (regression) testing strategy be?

**Comment by mboersma** [comment]
WRT regression testing, I think we're ok since components all have to opt-in to `pkg` updates. If we merge this, we can tag it as v0.5.0 (or v1.0.0?) and then update components individually as needed, where we will find any real breakage not covered by the unit tests here.

**Comment by bacongobbler** [comment]
As far as I know, none of the other components used github.com/deis/pkg/k8s which was the only package that was changed externally (via removal), and I don't think any package outside of deis/pkg was using that one. If they were, the migration path is for users to use k8s.io/client-go/rest and k8s.io/client-go/kubernetes to instantiate their kubernetes client.

No regression testing should be necessary. An [org-wide search](https://github.com/search?utf8=%E2%9C%93&q=org%3Adeis+deis%2Fpkg%2Fk8s&type=Code) comes up with no usage of github.com/deis/pkg/k8s, and the rest of the changes have no externally-facing changes.

**Review by mboersma — APPROVED** [review]

**Comment by mboersma** [comment]
I have a PR with similar changes to re-vendor k8s.io/kubernetes to v1.6.1, but this approach is more forward-looking.

**Pull request merged**
